### ISSUE TITLE
Laravel 5.3 strange pushing to queue issue?

### ISSUE THREAD

**Issue by geesper** [vladimir-yuldashev/laravel-queue-rabbitmq#102]
I'm using Laravel 5.3 and trying to push json to RabbitMQ. RabbitMQ is receiving the job rather than the payload, so I end up with data like this in my queue:

`{"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"commandName":"App\\Jobs\\QueueItem","command":"O:18:\"App\\Jobs\\QueueItem\":5:{s:10:\"\u0000*\u0000payload\";O:8:\"stdClass\":1:{s:5:\"Test\";s:17:\"Test data received\";}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:8:\"testing2\";s:5:\"delay\";N;}"}}
`

I just have a simple route set up like this in Laravel:

```
public function sendtoqueue() {
  $item = json_decode('{ "Testing" : "Test data received" }');
  $job = (new QueueItem($item))->onQueue('testing2');
  dispatch($job);
}
```

It's entirely possible I'm doing something wrong. I've looked through the queue documentation and can't seem to pinpoint what I'm missing. Additionally, here's my QueueItem job:

```
class QueueItem implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    protected $payload;
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($json) {
        $this->payload = $json;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle() {
        //
    }
}
```

Any help would be greatly appreciated! Thanks!

**Comment by geesper** [comment]
Well, I realized I am using this wrong! 

Sorry about the issue, looks like this is entirely a misunderstanding on my part of the laravel queues.

**Comment by IvanCaceres** [comment]
@geesper what did you end up doing? How do you transport a specific json payload instead of having the entire job serialized? Need this for cross service messaging where the consumer wouldn't be using PHP.

**Comment by vladimir-yuldashev** [comment]
@IvanCaceres I think you should use `Queue` facade instead of `Job` classes. You will be able to use custom payload.

**Comment by IvanCaceres** [comment]
Indeed, I ended up going with /Queue::pushRaw()
