### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by Rolice** [vladimir-yuldashev/laravel-queue-rabbitmq#103]
Hello,
We have configured server which supports communication via SSL. However, I have received an error for a `Broken pipe`. I am not sure and I cannot find any specific configuration that is needed to enable SSL communication with this pacakage.

Can you tell me what is needed to be done in order to initiate proper SSL connection?

I am not sure if an `AMQPSSLConnection` is needed over the currenty used `AMQPStreamConnection`? I am not sure yet how to explicitly require it, if necessary?

**Comment by vladimir-yuldashev** [comment]
Hi.

This is an [example](https://github.com/php-amqplib/php-amqplib/blob/master/demo/ssl_connection.php) of how to create an SSL connection. 

You can make changes and create PR.

**Comment by tristanbailey** [comment]
Hi @vladimir-yuldashev 

If I wanted to help on this, to add SSL connector. Would you suggest it went in the RabbitMQConnector setting up a AMQPSSLConnection if the extra config values were passed for ssl cert? Or a whole different ServiceProvider?

\VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector.php

thanks

**Comment by vladimir-yuldashev** [comment]
Hello, @tristanbailey

Yes, I think there should be an additional configuration key like `ssl` which should contain an array with `cacert` and other configuration options. Also, there should be some flag that secure connection should be used. 

Regarding service provider it's okay to put it on the same service provider you just need to determine there whether secure or default connection should be used.
