### ISSUE TITLE
Searchable array not used

### ISSUE THREAD

**Issue by jacob-v-dam** [vladimir-yuldashev/laravel-queue-rabbitmq#110]
Hello,

I created a `toSearchableArray` function for my model. This model returns the following:
```
$array                            = $this->toArray();
$array['from_address'] = $this->from_address->toSearchableArray();
$array['user']                 = $this->user->toSearchableArray();

return array_dot( $array );
```

So this should return my current model as an array and the user as an array aswel but it is converted to an dotted array. This is needed for Elastichsearch to search trough relations. When I start indexing my model the default data is send to Elasticsearch but not the `toSearchableArray` result.

**Comment by vladimir-yuldashev** [comment]
@jacob-v-dam I think this question is related to [Laravel](https://github.com/laravel/laravel).

**Comment by jacob-v-dam** [comment]
Well it returns the correct array. Formatted with dots but it isn't imported in Elasticsearch.
