### ISSUE TITLE
Add RPC Support

### ISSUE THREAD

**Issue by pmediaben** [vladimir-yuldashev/laravel-queue-rabbitmq#113]
Hi,

Is there any way to implement RPC using this package?

Thank you

**Comment by vladimir-yuldashev** [comment]
Yes.

**Comment by debugger84** [comment]
Can you show any examples how to do it, using your library?

**Comment by lucianobargmann** [comment]
> Yes.

This answer is like no answer. We appreciate the work and understand you must be busy, but some guidelines like "Use this type of configuration" would be really helpful. Anyways, I will take your "yes" answer and try to break it down into a more constructive reply in the next few days.

**Comment by lucianobargmann** [comment]
After a quick review on your code, the answer is **No.** 

There is no support to set up a reply-to queue and/or a correlation_id on your codebase, and there is no handling of these parameters using Laravel Queues. 

Yes, you can use AMQP lib directly, but that doesn't qualify laravel-queue-rabbitmq to be listed as "supports RPC"; 

Being honest - especially with a large user base is the best way to go, @vyuldashev

**Comment by amiranbarigreenweb** [comment]
@vyuldashev how can we use RPC protocol in this package?
