### ISSUE TITLE
How to use in Laravel's queue?

### ISSUE THREAD

**Issue by vietnguyen010** [vladimir-yuldashev/laravel-queue-rabbitmq#115]
I've completed the configuration but when I try to use with Laravel Queue API isn't work.

Here is my controller file

public function PostShare(Request $request)
    {
        if(strlen($request->status) > 0)
        {
            $wallJob = (new JobWallStatus(\Auth::user(),$request->status));
            dispatch($wallJob);
        }
        return redirect(route('home'));
    }

Here is my Job file
public function handle()
    {
        $wall = new wall();
        $wall->status = $this->status;
        $wall->user_id = $this->user->id;
        $wall->save();
    }

And nothing show in jobs table on my database.

Show how to use your library with Laravel Queue?

**Comment by vladimir-yuldashev** [comment]
Please, refer the [documentation](http://laravel.com/docs/5.4/queues).
