### ISSUE TITLE
Delete defered queues

### ISSUE THREAD

**Issue by marczahn** [vladimir-yuldashev/laravel-queue-rabbitmq#117]
Hi,

very nice and helpful library! Just one question: Is there any functionality to remove the queues for delayed jobs automatically?

**Comment by vladimir-yuldashev** [comment]
Hello, thank you. No, there is no such functionality.

**Comment by marczahn** [comment]
Hey,

thanks for the quick response. Are these defered queues used multiple times or just one time?

**Comment by vladimir-yuldashev** [comment]
They are reusable.

**Comment by marczahn** [comment]
ah ok. So actually I do not need to delete them, right? I was just afraid to end up with tenthousands of "zombie"-queues

**Comment by vladimir-yuldashev** [comment]
No need to delete them. In our production we have about 75 queues for about 2 years of using this package. It has no impact on performance.

**Comment by marczahn** [comment]
ok, great. Thank you very much. That helps me a lot

**Comment by marczahn** [comment]
Hi, I need to reopen this because we have ~2000 empty queues until. So we are slowly but steady running out of file descriptors.

**Comment by judgej** [comment]
The queues are given an expiry that is double the delay they service. They will delete themselves when that expiry is reached. I am hoping that applies only of they are empty, and I'm hoping that when a new delayed job is added, when checking if the queue already exists, that it has more than a few mS of time left before it expires. (On my TODO list to check these things out)

**Comment by adm-bome** [comment]
@judgej your commenting on a issue from 2017. This library has evolved sinds then.....

Your question does not reflect that specific version of the library in that specific time period, nor the laravel version.

Notes:

Please don't use this as a forum.
Please don't use issues as a 'what you have to do list'.
Don't create issues for every question you have about life.


 

But as i am... a little explanation..

Auto queue expire and cleanup, will only trigger when idle for a given time. Any message entering or leaving the queue, resets this counter.

START READING:
 - THE RABBITMQ MANUAL / DOCUMENTATION. 
 - LARAVEL DOCUMENTATION FOR QUEUING.

I know its alot to ask. 
But i won't explain all the queuing concepts or possibilities, this world has to offer.

**Comment by judgej** [comment]
I was hoping the comment was useful to @marczahn 

The latest version of this package should deal with the 2000-odd queue problem he has.
