### ISSUE TITLE
Stop or Update Deferred Queue

### ISSUE THREAD

**Issue by chrissupnet29** [vladimir-yuldashev/laravel-queue-rabbitmq#120]
Hello,

Good day! I'm still new in using your library, I just have one question. Is there a way to stop or update deferred queue?

Thanks!

**Comment by vladimir-yuldashev** [comment]
Hi. What to you mean by stopping deferred queue? The worker should listen only for main queue while the deferred ones will route messages in particular time. If you want to delete deferred queue you can do it using RabbitMQ management module.

**Comment by chrissupnet29** [comment]
Hello,

I'm sorry for the incorrect wording. What I mean is for example, I have a job that needs to be executed(for example, 1 hr from now). With that, I need to use the `delay()` method. Is there a way to Purge the existing Job when I want to update the value passed to `delay()` method of the same Job? Let's say originally, I want to execute it 1 hr from now. Then I changed my mind, I want it to execute 10 mins from now.

**Comment by vladimir-yuldashev** [comment]
Now I understand you. No, you can’t do this using Laravel Queue. The only way you can do this is using management plugin :) just purge your query. It’s the only way I think.

**Comment by chrissupnet29** [comment]
I see, thanks!
