### ISSUE TITLE
Queue Worker - Multiple Queues

### ISSUE THREAD

**Issue by milsanore** [vladimir-yuldashev/laravel-queue-rabbitmq#122]
Hi Vladimir, thank you for building this library - I'm very excited to plug it in. 
I come from a fintech background (TIBCO EMS, 29West, etc), where it's common to separate message traffic based on 'topic' (e.g. product-created / product-updated / etc) into separate queues. Can I make the queue worker listen to multiple queues using your library?
Thanks!

**Comment by vladimir-yuldashev** [comment]
Sure. 
If you dispatch jobs to multiple queues, for example:
```php
dispatch((new FirstJob)->onQueue('foo'));
dispatch((new SecondJob)->onQueue('bar'));
```
You need to run two workers:
```php artisan queue:work --queue=foo```
and
```php artisan queue:work --queue=bar```
