### ISSUE TITLE
Consumer queue when a strange problems

### ISSUE THREAD

**Issue by smj227227** [vladimir-yuldashev/laravel-queue-rabbitmq#123]
In MAC consumption speed can reach 800-900 / s, but in the server always unable to break through 25 / s consumption rate, even is higher than the MAC environment consistent server hardware, still cannot break through 25 / s

![1](https://user-images.githubusercontent.com/6949292/27237894-5d81f01a-52fd-11e7-90e7-2be4edd2bd17.jpeg)
![2](https://user-images.githubusercontent.com/6949292/27237892-5d694da8-52fd-11e7-8c16-548a290b8856.jpeg)

**Comment by vladimir-yuldashev** [comment]
It depends of how many workers you have, what your jobs actually do. 
Is the problem it taking job from the queue, acking it or something else.

We have a huge queue and about 32 workers, and it works fast. 

Also, I recommend you to build a cluster and put slave nodes in RAM and connect to them. It will also increase the speed of interaction between your application and RabbitMQ.

**Comment by smj227227** [comment]
In the consumer when the queue output only, do not interact with the database, which is strange for me, MAC in sync with the server code, MAC consumption speed can reach 800 / s, but even if it is a good server can only run to 25 / s, server hardware than the MAC also is unable to avoid

Below is the consumption of the server and the MAC code, only do the output

![3](https://user-images.githubusercontent.com/6949292/27249983-8c81d1ca-5355-11e7-840b-b8439a802a97.jpeg)

**Comment by halechen** [comment]
same question！
one worker ， only output ， max 25/s

**Comment by halechen** [comment]
> In the consumer when the queue output only, do not interact with the database, which is strange for me, MAC in sync with the server code, MAC consumption speed can reach 800 / s, but even if it is a good server can only run to 25 / s, server hardware than the MAC also is unable to avoid
> 
> Below is the consumption of the server and the MAC code, only do the output
> 
> ![3](https://user-images.githubusercontent.com/6949292/27249983-8c81d1ca-5355-11e7-840b-b8439a802a97.jpeg)

solved???
