### ISSUE TITLE
L4.2: Extremely low publishing & consuming message rate

### ISSUE THREAD

**Issue by lephleg** [vladimir-yuldashev/laravel-queue-rabbitmq#128]
I'm trying to use the driver with L4.2 but I'm encountering a ridiculously low message rate of 20/s when publishing jobs:

![rabbitmq-message-rate-throttling](https://user-images.githubusercontent.com/4146200/28111417-0987c574-66fe-11e7-830d-b209f98f629e.png)

I'm using the official docker image for RabbitMQ (https://hub.docker.com/_/rabbitmq/) along with its management tool (rabbitmq:3.6.10-management).

My configs are the following:

```
'rabbitmq' => array(
            'driver'    => 'rabbitmq',
            'host'      => $_ENV['RABBITMQ_HOST'],
            'port'      => $_ENV['RABBITMQ_PORT'],
            'vhost'     => $_ENV['RABBITMQ_VHOST'],
            'login'     => $_ENV['RABBITMQ_LOGIN'],
            'password'  => $_ENV['RABBITMQ_PASSWORD'],
            'queue'     => $_ENV['RABBITMQ_QUEUE'],

            // create the exchange if not exists
            'exchange_declare' => true,
            // create the queue if not exists and bind to the exchange
            'queue_declare_bind' => true,

            'queue_params' => [
                'passive' => false,
                'durable' => true,
                'exclusive' => false,
                'auto_delete' => false,
            ],

            'exchange_params' => [
                'name' => null,
                // more info at http://www.rabbitmq.com/tutorials/amqp-concepts.html
                'type' => 'direct',
                'passive' => false,
                'durable' => true, // the exchange will survive server restarts
                'auto_delete' => false,
            ],
```

I've set durable to false but it had no effect at all. Am I missing something here? 
Additionally, when I'm trying to consume the queue the Consumer ack is much lower at 2.0/s...!
Any suggestions on what it could be wrong or how I could troubleshoot this?

**Comment by lephleg** [comment]
Solution found using this rejected PR:

https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/pull/45

Please reconsider merging it.

**Comment by vladimir-yuldashev** [comment]
@lephleg Should I wait for a PR from you?

**Comment by lephleg** [comment]
@vladimir-yuldashev I'll need to run some tests before releasing this to my production.

Using `php artisan queue::work --daemon`  instead of `php artisan queue::listen` improved the consuming rate to 20/s, which seems fair for my local.
