### ISSUE TITLE
lumen 5.4 is not work

### ISSUE THREAD

**Issue by wangwindows** [vladimir-yuldashev/laravel-queue-rabbitmq#129]
I added this line in bootstrap/app.php
`$app->register(VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::class);
`
and I write a job:
```
class MqDataToEsJob extends Job
{
    protected $mqData;
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($mqData)
    {
        echo "get data\n";
        $this->mqData = $mqData;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        //
        var_dump($this->mqData);
    }
}
```

then, I try to run this command:
php artisan queue:work

A error had been reported:
[InvalidArgumentException]  
  No connector for []       

hope someone can help me, thanks.

**Comment by vladimir-yuldashev** [comment]
I guess you should copy `config/queue.php` from vendor and add `rabbitmq` connection configuration.
