### ISSUE TITLE
No connector for [rabbitmq]

### ISSUE THREAD

**Issue by Dreaw** [vladimir-yuldashev/laravel-queue-rabbitmq#36]
HI,
I have a problem, I get error message "No connector for [rabbitmq]".

I saw this topic (https://github.com/fintech-fab/laravel-queue-rabbitmq/issues/32), but I don't see solution.

Thanks for any response.
Martin

**Comment by Gallaecio** [comment]
For future reference, I had this issue and it turned out I was missing the registration call on my `app.php` file:
```php
$app->register(VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::class);
```
