### ISSUE TITLE
Does this library only support sending messages to one exchange?

### ISSUE THREAD

**Issue by atrauzzi** [vladimir-yuldashev/laravel-queue-rabbitmq#41]
Just a quick question about how things are laid out.  I'm trying to plan my RabbitMQ setup and need to know if I can target different exchanges with this library.

**Comment by winfan** [comment]
Push a raw payload onto the queue. 
 how to pushRaw function method

**Comment by vladimir-yuldashev** [comment]
1 exchange per one connect, but you can declare several queue connections and use it by "Queue::connection('rabbitmq2')"

**Comment by AidasK** [comment]
This doesn't sound like a good and flexible solution
