### ISSUE TITLE
PhpAmqpLib\Exception\AMQPProtocolConnectionException·ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.

### ISSUE THREAD

**Issue by raghav-g** [vladimir-yuldashev/laravel-queue-rabbitmq#43]
vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:685 PhpAmqpLib\Connection\AbstractConnection::connection_close
    [internal] call_user_func
    vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:194 PhpAmqpLib\Channel\AbstractChannel::dispatch
    vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:393 PhpAmqpLib\Channel\AbstractChannel::wait
    vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:212 PhpAmqpLib\Connection\AbstractConnection::connect
    vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:179 PhpAmqpLib\Connection\AbstractConnection::__construct
    vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php:41 PhpAmqpLib\Connection\AMQPStreamConnection::__construct
    vendor/fintech-fab/laravel-queue-rabbitmq/src/FintechFab/LaravelQueueRabbitMQ/Queue/Connectors/RabbitMQConnector.php:25 FintechFab\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector::connect
    vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:133 Illuminate\Queue\QueueManager::resolve
    vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:113 Illuminate\Queue\QueueManager::connection
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:149 Illuminate\Queue\Worker::pop
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:109 Illuminate\Queue\Console\WorkCommand::runWorker
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:71 Illuminate\Queue\Console\WorkCommand::fire
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/Container.php:503 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Console/Command.php:150 Illuminate\Console\Command::execute
    vendor/symfony/console/Command/Command.php:256 Symfony\Component\Console\Command\Command::run
    vendor/laravel/framework/src/Illuminate/Console/Command.php:136 Illuminate\Console\Command::run
    vendor/symfony/console/Application.php:838 Symfony\Component\Console\Application::doRunCommand
    vendor/symfony/console/Application.php:189 Symfony\Component\Console\Application::doRun
    vendor/symfony/console/Application.php:120 Symfony\Component\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107 Illuminate\Foundation\Console\Kernel::handle
    artisan:36 [main]

**Comment by raghav-g** [comment]
This issue weirdly started happening from yesterday and it is appear to be happening while closing connection. What could be the issue here?

**Comment by vladimir-yuldashev** [comment]
Not sure. How to replay this bug?

**Comment by andrefigueira** [comment]
Experiencing this issue now also, not sure why... Seems to only be happening on one specific server.
