### ISSUE TITLE
Support for laravel 5.2

### ISSUE THREAD

**Issue by d-ivaschenko-parc** [vladimir-yuldashev/laravel-queue-rabbitmq#44]
Where there be support for Laravel 5.2 ("laravel/framework": "5.2.*@dev") ?

**Comment by vladimir-yuldashev** [comment]
Hi there,

will update this package with support for 5.2 this weekend. But this package will be moved to another vendor and current package will be deprecated. Will update this information soon.

**Comment by vladimir-yuldashev** [comment]
Okay, I just created a branch for 5.2 support. Can you please test it? Also, notice that vendor has been changed from "FintechFab" to "VladimirYuldashev"

https://packagist.org/packages/vladimir-yuldashev/laravel-queue-rabbitmq#5.2.x-dev

**Comment by mubin-khalid** [comment]
Hi @vladimir-yuldashev: that's really a nice package, thanks for that(I've used it with _L5.1_).
I'm working with __L5.2__ now, and tried to install package(s [both-older and newer one]) but getting the same response

Here is output

    PS /sites> composer require vladimir-yuldashev/laravel-queue-rabbitmq
    Using version ^5.1 for vladimir-yuldashev/laravel-queue-rabbitmq
./composer.json has been updated
    > php artisan clear-compiled
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for vladimir-yuldashev/laravel-queue-rabbitmq ^5.1 -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[5.1].
        - Conclusion: remove laravel/framework v5.2.5
        - Conclusion: don't install laravel/framework v5.2.5
        - vladimir-yuldashev/laravel-queue-rabbitmq 5.1 requires illuminate/queue 5.1.* -> satisfiable by illuminate/queue[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.
1.8].
        - don't install illuminate/queue v5.1.1|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.13|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.16|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.2|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.20|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.22|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.25|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.28|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.6|don't install laravel/framework v5.2.5
        - don't install illuminate/queue v5.1.8|don't install laravel/framework v5.2.5
        - Installation request for laravel/framework == 5.2.5.0 -> satisfiable by laravel/framework[v5.2.5].

any clue or thoughts?

**Comment by vladimir-yuldashev** [comment]
Hello @mubin-khalid, try to use https://packagist.org/packages/vladimir-yuldashev/laravel-queue-rabbitmq#5.2.x-dev this version as I mentioned above.

**Comment by mubin-khalid** [comment]
@vladimir-yuldashev : tried these in ````composer.json````
    "vladimir-yuldashev/laravel-queue-rabbitmq": "5.2"
and
    "vladimir-yuldashev/laravel-queue-rabbitmq": "5.2@dev"

but getting this response from composer

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package vladimir-yuldashev/laravel-queue-rabbitmq could not be found in any version, there may be a typo in the package name.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by samparsky** [comment]
Please have you been able to solve it?

**Comment by mubin-khalid** [comment]
@samparsky, not yet. waiting for @vladimir-yuldashev 's response.

**Comment by vladimir-yuldashev** [comment]
@mubin-khalid , @samparsky Guys it works if you write like this:

    "require": {
        "vladimir-yuldashev/laravel-queue-rabbitmq": "5.2@dev"
    },

**Comment by mubin-khalid** [comment]
@vladimir-yuldashev : not working ````"vladimir-yuldashev/laravel-queue-rabbitmq": "5.2@dev"````, here is snapshot
![error](https://cloud.githubusercontent.com/assets/5962518/12572565/04baa1de-c410-11e5-9a81-513e02c9f764.PNG)

**Comment by mubin-khalid** [comment]
@vladimir-yuldashev, @samparsky, got it working. Here is the thing that you need to make it run

````"vladimir-yuldashev/laravel-queue-rabbitmq": "5.2.*"````

and run ````composer update````

**Comment by danjohnson95** [comment]
Has support for 5.2 been removed? I'm getting

`The requested package vladimir-yuldashev/laravel-queue-rabbitmq could not be found in any version, there may be a typo in the package name.`

when `"vladimir-yuldashev/laravel-queue-rabbitmq": "5.2.*"` is in my composer file.

**Comment by minkbear** [comment]
@danjohnson95 try `"vladimir-yuldashev/laravel-queue-rabbitmq": "5.2.*@dev"`

**Comment by nicksnellockts** [comment]
It looks like the release() method is not working with Laravel 5.2
