### ISSUE TITLE
 Class 'VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider' not found

### ISSUE THREAD

**Issue by deepak-kumar** [vladimir-yuldashev/laravel-queue-rabbitmq#46]
After running composer install successfully and updating app.php it throws following error. I have mad sure that configs are correct. I am using Laravel 5.1

  [Symfony\Component\Debug\Exception\FatalErrorException]                                       
  Class 'VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider' not found

**Comment by deepak-kumar** [comment]
Anything? Suggestions?

**Comment by vladimir-yuldashev** [comment]
Please update again

**Comment by deepak-kumar** [comment]
Thank you very much. It worked.

**Comment by sudhirkumarhere** [comment]
Facing same problem :

Class 'VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::class' not found

I am using Laravel 4.2
