### ISSUE TITLE
How to get the attempt count? And how to delete a job?

### ISSUE THREAD

**Issue by BlazeNikhilesh** [vladimir-yuldashev/laravel-queue-rabbitmq#47]
I am trying $this->attempt(), but it always gives me 0. Is it something that I am missing out?

**Comment by enVolt** [comment]
I've been facing weird issue. Sometime it is able to get $this->attempt(), but some time it is returned 0.
Even in payload, there is no key for attempt. For some case it does. I'm not yet able to figure out when there is attempt count, when there isn't.

Am I missing something?

**Comment by vladimir-yuldashev** [comment]
attempt is default 0 if not present. When you do $this->release() or $job->release() it increments its "attempts" value in payload. But by default there is no attempts in payload.

**Comment by vladimir-yuldashev** [comment]
You can delete job by $this->delete() or $job->delete()
