### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by marabesi** [vladimir-yuldashev/laravel-queue-rabbitmq#48]
When I run `composer require vladimir-yuldashev/laravel-queue-rabbitmq` I get the error message : 

```                                                                                                                                               [InvalidArgumentException]                                                                                                                          
  Could not find package vladimir-yuldashev/laravel-queue-rabbitmq at any version for your minimum-stability (stable). Check the package spelling or  
   your minimum-stability
```

Have you guys ever seen that ?

**Comment by nuffstuff** [comment]
It could be due to the changeover on php-amqplib. I get this warning now:

`Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.`

**Comment by digitalkreativ** [comment]
I got that when installing the preferred distribution of laravel via composer. It installs laravel **5.2** . The current latest version of this package requires laravel **5.1** . 

You can install that with the following composer command

    composer create-project laravel/laravel project-name "5.1.*"

**Comment by vladimir-yuldashev** [comment]
Just tagged 5.2
