### ISSUE TITLE
Use php-amqplib/php-amqplib instead of videlalvaro/php-amqplib

### ISSUE THREAD

**Issue by sebwas** [vladimir-yuldashev/laravel-queue-rabbitmq#49]
As the latter one is officially abandoned (and marked as such in packagist) the _new_ maintained version **php-amqplib/php-amqplib** should be used instead.

**Comment by fusion52** [comment]
same issue.

**Comment by tristanbailey** [comment]
It looks like so far it is just the package namespace and owners that has been changed so, should be a small PR to update it. Would you be interested in me or someone doing the work?
In order to clear the composer and warning going forward:

> Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

**Comment by sebwas** [comment]
Hi Tristan, yes that is right. I already created such a PR, please see PR #50 for details.

**Comment by atrauzzi** [comment]
+1

**Comment by vladimir-yuldashev** [comment]
Done!
