### ISSUE TITLE
Service provider can not be found on Laravel 4.2

### ISSUE THREAD

**Issue by muratak18** [vladimir-yuldashev/laravel-queue-rabbitmq#51]
Hi,
i installed the package via composer then added it to providers array but i get this error :
`Class 'VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider' not found`

Is there a different way to add service provider ?

**Comment by vladimir-yuldashev** [comment]
Try it now, please
