### ISSUE TITLE
laravel 5.2 delay not working

### ISSUE THREAD

**Issue by pepijnblom** [vladimir-yuldashev/laravel-queue-rabbitmq#52]
Hi Vladimir,

It seems like the delay() option is not working for us.
Is there anything that needs to be added to RabbitMq or configured in your package to make this work?

**Comment by pepijnblom** [comment]
So I now notice it's creating extra queue's depending on the delay defined. Not sure why it was not doing that before. However, these queue's do not seem to be filled?

![screen shot 2016-03-24 at 12 56 35](https://cloud.githubusercontent.com/assets/6009489/14016357/0a2d0c00-f1c0-11e5-9fc5-d7b05d3909e9.png)

**Comment by akeinhell** [comment]
[Кусок кода](https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/v5.2/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/RabbitMQQueue.php#L82)

Если ставим в очередь через exchange, то до очереди сообщение не доходит
Если пушим сообщение сразу в очередь, то все норм работает

`$this->channel->basic_publish($message, $queue, $queue);`

**Comment by pepijnblom** [comment]
@akeinhell Thanks for the fix!

@vladimir-yuldashev Could you incorporate this?

**Comment by vladimir-yuldashev** [comment]
Merged and in tag 5.2 already. Thanks!
