### ISSUE TITLE
How to listen for messages?

### ISSUE THREAD

**Issue by AidasK** [vladimir-yuldashev/laravel-queue-rabbitmq#55]
I have created exclusive fanout queue, but laravel "artisan queue:listen" restarts rabbitmq connection every 3 seconds. Because of this the old queue is deleted and it creates a new queue.
Is there a better way to listen for these messages? Just subscribe and wait

**Comment by vladimir-yuldashev** [comment]
I think someone need to provide another artisan command specially for RabbitMQ. "queue:listen" works Caravel-Way now.

**Comment by jndlkaran** [comment]
Does this plugin work for Laravel 4.2 version. Trying to install but giving an error

**Comment by vladimir-yuldashev** [comment]
@jndlkaran provide log please.
