### ISSUE TITLE
Attempts counter + queue:retry issue

### ISSUE THREAD

**Issue by drcreazy** [vladimir-yuldashev/laravel-queue-rabbitmq#57]
Hi Vladimir, thank you for such great connector!

I found that Laravel default retry command **artisan queue:retry** used `$payload['attempts']` counter to reset attempts. 
[https://github.com/illuminate/queue/blob/master/Console/RetryCommand.php#L75](https://github.com/illuminate/queue/blob/master/Console/RetryCommand.php#L75)

There a slightly different key for attempts in RabbitMQJob `$payload['data']['attempts']`
[https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/master/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php#L83](https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/master/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php#L83)

So in my case **artisan queue:retry** command not worked fine until I add 
`
        if (isset($payload['data']['attempts'])) {
            $payload['data']['attempts'] = 0;
        }
` 
into RetryCommand::resetAttempts.

Seems we have to use something like `$this->setMeta($payload, 'attempts', 1)` creating payload, 
[https://github.com/illuminate/queue/blob/master/RedisQueue.php#L217](https://github.com/illuminate/queue/blob/master/RedisQueue.php#L217) 

What do you think?

**Comment by vladimir-yuldashev** [comment]
Will review that when I have some free time

**Comment by adrenth** [comment]
Got the same issue here. It is not possible to retry a job because 'attempts' could not be retrieved from the payload body.

Have you looked in this issue already?

**Comment by vladimir-yuldashev** [comment]
Merged and pushed to 5.2
