### ISSUE TITLE
Undefined index: job

### ISSUE THREAD

**Issue by Borkache** [vladimir-yuldashev/laravel-queue-rabbitmq#60]
exception 'ErrorException' with message 'Undefined index: job' in /var/www/api-v1.gdmfx.com/httpdocs/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php:96

got too many of this errors, got same when used redis as queue, but on laravel site developers told that it can be in case of cross match between cache and queue jobs. What the problem is here maybe laravel side again? 

I used this versions 
"laravel/framework": "5.1.*",
"vladimir-yuldashev/laravel-queue-rabbitmq": "5.1",

Thanks!

**Comment by Borkache** [comment]
seems problem is here 
$body = $this->message->body;
		$body = json_decode($body, true);

		$attempts = $this->attempts();

		// write attempts to body
		$body['data']['attempts'] = $attempts + 1;

		$job = $body['job'];
		$data = $body['data'];

in VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob, so maybe can be some kind of situations with wrong message content and maybe you can add some checker

**Comment by vladimir-yuldashev** [comment]
Cannot replay the issue. It works for me. Can you provide examples?

**Comment by Borkache** [comment]
trying to catch it near 2 weeks already , I use standard facades for queue in laravel but there is some strange situation when the record in queue is blank , will try to catch again , if will be lucky will paste here, thanks for feedback

**Comment by adrenth** [comment]
Got the same issues with the `Undefined index: job`, this is still an issue. For some reason the message body cannot be extracted from the message body. This occurs randomly. As of now I cannot reproduce this issue. But this issue should be re-opened.

**Comment by hillelcoren** [comment]
FYI... we're seeing this error randomly as well, we're using redis.

**Comment by vladimir-yuldashev** [comment]
@hillelcoren How does applies to this driver?

**Comment by vladimir-yuldashev** [comment]
@adrenth Try to catch the exception and provide stack trace, please.

**Comment by hillelcoren** [comment]
The problem may be with Laravel rather than this specific driver.

**Comment by hillelcoren** [comment]
You can see a stack here: https://github.com/laravel/framework/issues/9555

**Comment by vladimir-yuldashev** [comment]
I did not get this kind of error for about 3 years using this driver in production.

@hillelcoren Yeah, @cabloo answered there

> For other people who come across this problem: I had the same issue after I forgot to add the 'Illuminate\Queue\SerializesModels' to a Job/Command class. Earlier in the Job/Command pipeline, the json_encode function doesn't know how to serialize Jobs that have models without that function, so json_encode on the array containing the job returns false.

May be this is the issue?

**Comment by hillelcoren** [comment]
Thanks, we tracked down the problem. There was an error processing the job payload.

**Comment by wangxiaojun111** [comment]
@hillelcoren  Hi,Can you say when this happens? I also encountered this problem, did not find a way to reproduce

**Comment by hillelcoren** [comment]
In our case the job payload was failing to be decoded.

**Comment by wangxiaojun111** [comment]
Did you solve it? How to solve it? @hillelcoren

**Comment by hillelcoren** [comment]
We fixed it by removing data from the job payload, in our case it was a raw PDF file which caused problems.

**Comment by wangxiaojun111** [comment]
all right，i also fixed it by removing data from the job payload ，thanks

**Comment by defaye** [comment]
I avoided serialization errors by removing some of the instantiation of problem code from the job's `__construct()` to the `handle()` method.
