### ISSUE TITLE
Can you use semantic versioning?

### ISSUE THREAD

**Issue by adrenth** [vladimir-yuldashev/laravel-queue-rabbitmq#61]
Hi Vladimir,

Thanks a lot for merging and pushing #59. That solved a lot of issues in my applications. But why don't you use semantic versioning for your composer package?

To update the package (with solved issues) I needed to change my composer requirement from:

`"vladimir-yuldashev/laravel-queue-rabbitmq": "5.2"`

to:

`"vladimir-yuldashev/laravel-queue-rabbitmq": "dev-master#ec2a55e86c2341716e906411b0c2b3084917b638"`

Just to force our deployment server to update this specific package to it's latest version. The package with version "5.2" was already cached so not updated. It would be a lot easier if you merged this issue and tagged the `origin/v5.2` branch with `5.2.1`. This solves a lot of updating issues.

What are your thoughts about this?

**Comment by vladimir-yuldashev** [comment]
Hi there,

when I was deciding how to make versioning, firstly I was seeking for the easiest way to understand and migrate between Laravel versions. So, I preferred to use Laravel versions instead. So you will need just to put your Laravel version for this package and get updates if there are so.

**Comment by adrenth** [comment]
I understand the different branches for the different Laravel versions. But now every user should remove your package and then add it again to apply the updates? I don't think that should be the correct way.

**Comment by vladimir-yuldashev** [comment]
Why do users need to remove the package and add it again?

**Comment by adrenth** [comment]
When I perform a `composer update vladimir-yuldashev/laravel-queue-rabbitmq` nothing happens because composer detects cached version 5.2. 

After you change code and push it to github, you should tag it with a different version so that composer knows it should fetch the new version instead of the cached one.

**Comment by vladimir-yuldashev** [comment]
I got you, it gives me newer version after several minutes after tagging :)
