### ISSUE TITLE
Delay function does not work

### ISSUE THREAD

**Issue by tarkis** [vladimir-yuldashev/laravel-queue-rabbitmq#62]
Hello @vladimir-yuldashev ,

here is the problem with delay function. The problem is that delay queue has a static value "x-dead-letter-exchange" set the same as "x-dead-letter-routing-key". 

Simple example:
exchange = amq.direct
queues assigned to the same exchange (amq.direct) = [test, test_deferred_10]
The problem is with test_deferred_10 argument x-dead-letter-exchange, because once its done with TTL it searches for this exchange "test" and not he original one amq.direct. All our queues are assigned to amq.direct and thats why it cant find the queue defined in x-dead-letter-routing-key

It looks like this PL #56 should help

**Comment by vladimir-yuldashev** [comment]
Released in 5.2
