### ISSUE TITLE
Queue:failing not being triggered when Job fails

### ISSUE THREAD

**Issue by lelu85** [vladimir-yuldashev/laravel-queue-rabbitmq#64]
If I just launch a simple job with an exception in it, it is supposed to be a failure due to Laravel documentation but the method Queue:failing does not launch its callback. 
Queue:after, and Queue:before though, are working perfectly.

I thing failed_jobs table insert is even not working and I don't see any approach on the code. All this  functionalities should be developed by scratch?

**Comment by pawaroti** [comment]
I think it was related to this issue whitch is fixed now. 

https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/issues/63

**Comment by vladimir-yuldashev** [comment]
Can anyone confirm that it is fixed already?

**Comment by dustindoiron** [comment]
This works for us on laravel 5.2.39 and laravel-queue-rabbitmq 5.2 (current).
