### ISSUE TITLE
Undefined index: command

### ISSUE THREAD

**Issue by rdrenth** [vladimir-yuldashev/laravel-queue-rabbitmq#66]
When I use [Queued Event Listeners](https://laravel.com/docs/5.2/events#queued-event-listeners) I get the error "Undefined index: command" when the handle() function of that event listener fails / throws an exception. 

The method `release()` in the class `VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob` expect there to be `$body['data']['command']`, but when using Queued Event Listeners, that is not the case, the payload is actually:

`{
    "job": "Illuminate\\Events\\CallQueuedHandler@call",
    "data": {
        "class": "App\\Listeners\\Frontend\\Auditfile\\AuditfileUploadedListener",
        "method": "handle",
        "data": "a:1:{i:0;O:47:\"App\\Events\\Frontend\\Auditfile\\AuditfileUploaded\":1:{s:58:\"\u0000App\\Events\\Frontend\\Auditfile\\AuditfileUploaded\u0000auditfile\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:30:\"App\\Models\\Auditfile\\Auditfile\";s:2:\"id\";i:4;}}}"
    }
}`

Compare that to the payload of a normal Job:
`{"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"commandName":"App\\Jobs\\ImportAuditfileJob","command":"O:27:\"App\\Jobs\\ImportAuditfileJob\":5:{s:38:\"\u0000App\\Jobs\\ImportAuditfileJob\u0000auditfile\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:30:\"App\\Models\\Auditfile\\Auditfile\";s:2:\"id\";i:9;}s:10:\"connection\";N;s:5:\"queue\";N;s:5:\"delay\";N;s:6:\"\u0000*\u0000job\";N;}"}}`

I hope this is enough information

**Comment by vladimir-yuldashev** [comment]
Yes. In 5.2 already.

**Comment by nanophp** [comment]
> Yes. In 5.2 already.

@vyuldashev I'm using Laravel 6.6 but I have the same problem.

**Comment by vyuldashev** [comment]
@nanophp Package version?

**Comment by nanophp** [comment]
> @nanophp Package version?

the package version is 9.1.2  and laravel version is 6.6.0

**Comment by vyuldashev** [comment]
Can you provide payload of the job which fails, please?

**Comment by nanophp** [comment]
> Can you provide payload of the job which fails, please?

to be honest it's the scratch project and I have just using just 

> php artisan queue:work --tries=2 rabbitmq --queue=welcome_email --stop-when-empty

```
this command it returns to me 

   ErrorException  : Undefined index: queue
```

**Comment by nanophp** [comment]
@vyuldashev 

        ```
'rabbitmq' => [

            'driver' => 'rabbitmq',
            'queue' => env('RABBITMQ_QUEUE', 'default'),
            'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,

            'hosts' => [
                [
                    'host' => env('RABBITMQ_HOST', 'rabbitmq'),
                    'port' => env('RABBITMQ_PORT', 5672),
                    'user' => env('RABBITMQ_USER', 'user'),
                    'password' => env('RABBITMQ_PASSWORD', 'secret_password'),
                    'vhost' => env('RABBITMQ_VHOST', '/'),
                ],
            ],

            'options' => [
                'ssl_options' => [
                    'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                    'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                    'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                    'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                    'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
                ],
            ],

            /*
             * Set to "horizon" if you wish to use Laravel Horizon.
             */
            'worker' => env('RABBITMQ_WORKER', 'default'),

        ],
```

**Comment by vyuldashev** [comment]
@nanophp Can you put `dump` [here](https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/v9.0/src/Queue/Jobs/RabbitMQJob.php#L55)?

**Comment by nanophp** [comment]
@vyuldashev 

this is also my docker-compose.yml file

```
rabbitmq:
    container_name: skilldeer-rabbitmq
    image: bitnami/rabbitmq:3.7.14
    user: root
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-vol:/bitnami
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: secret_password
```

**Comment by vyuldashev** [comment]
@nanophp Well, you are using configuration example from upcoming v10, switch to v9 branch and refer configuration from its branch

**Comment by nanophp** [comment]
@vyuldashev my error dump is 

```
 ErrorException  : Undefined index: queue

  at /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:39
    35|     {
    36|         $this->context = $context;
    37| 
    38|         $this->queueName = $config['queue'] ?? $config['options']['queue']['name'];
  > 39|         $this->queueOptions = $config['options']['queue'];
    40|         $this->queueOptions['arguments'] = isset($this->queueOptions['arguments']) ?
    41|             json_decode($this->queueOptions['arguments'], true) : [];
    42| 
    43|         $this->exchangeOptions = $config['options']['exchange'];

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: queue", "/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php", [Object(Enqueue\AmqpLib\AmqpContext)])
      /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:39

  2   VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::__construct(Object(Enqueue\AmqpLib\AmqpContext))
      /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Connectors/RabbitMQConnector.php:80

  Please use the argument -v to see more details.

```

**Comment by nanophp** [comment]
> @nanophp Well, you are using configuration example from upcoming v10, switch to v9 branch and refer configuration from its branch

"vladimir-yuldashev/laravel-queue-rabbitmq": "^9.1"
"vladimir-yuldashev/laravel-queue-rabbitmq": "^10" like this?

**Comment by vyuldashev** [comment]
@nanophp https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/v9.0/config/rabbitmq.php

**Comment by nanophp** [comment]
> @nanophp https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/v9.0/config/rabbitmq.php

can I use this configuration array using in queue.php into connections array or it needs to be create rabbitmq.php

**Comment by vyuldashev** [comment]
@nanophp Put it as a connection inside `queue.php`

**Comment by nanophp** [comment]
> @nanophp Put it as a connection inside `queue.php`

yes I did it, but I got the same errror

**Comment by vyuldashev** [comment]
@nanophp I need your job payload. And run queue:work with -vvv

**Comment by nanophp** [comment]
> @nanophp I need your job payload. And run queue:work with -vvv


   ErrorException  : Undefined index: queue

  at /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:39
    35|     {
    36|         $this->context = $context;
    37| 
    38|         $this->queueName = $config['queue'] ?? $config['options']['queue']['name'];
  > 39|         $this->queueOptions = $config['options']['queue'];
    40|         $this->queueOptions['arguments'] = isset($this->queueOptions['arguments']) ?
    41|             json_decode($this->queueOptions['arguments'], true) : [];
    42| 
    43|         $this->exchangeOptions = $config['options']['exchange'];

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: queue", "/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php", [Object(Enqueue\AmqpLib\AmqpContext)])
      /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:39

  2   VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::__construct(Object(Enqueue\AmqpLib\AmqpContext))
      /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Connectors/RabbitMQConnector.php:80

  3   VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector::connect()
      /var/www/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:157

  4   Illuminate\Queue\QueueManager::resolve("rabbitmq")
      /var/www/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:138

  5   Illuminate\Queue\QueueManager::connection("rabbitmq")
      /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:118

  6   Illuminate\Queue\Worker::daemon("rabbitmq", "welcome_email", Object(Illuminate\Queue\WorkerOptions))
      /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:112

  7   Illuminate\Queue\Console\WorkCommand::runWorker("rabbitmq", "welcome_email")
      /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:96

  8   Illuminate\Queue\Console\WorkCommand::handle()
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  9   call_user_func_array([])
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  10  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php:34

  11  Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  12  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  13  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:590

  14  Illuminate\Container\Container::call()
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php:202

  15  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/vendor/symfony/console/Command/Command.php:255

  16  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php:189

  17  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php:1011

  18  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php:272

  19  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php:148

  20  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  21  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131

  22  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/artisan:37

**Comment by vyuldashev** [comment]
@nanophp You have problems with connection configuration.

**Comment by nanophp** [comment]
> @nanophp You have problems with connection configuration.

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
    */

    'default' => env('QUEUE_CONNECTION', 'sync'),

    /*
    |--------------------------------------------------------------------------
    | Queue Connections
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Laravel. You are free to add more.
    |
    | Drivers: "sync", "database", "beanstalkd", "sqs", "redis", "null"
    |
    */

    'connections' => [

        'rabbitmq' => [


            'driver' => 'rabbitmq',
            /*
             * Set to "horizon" if you wish to use Laravel Horizon.
             */
            'worker' => env('RABBITMQ_WORKER', 'default'),
            'dsn' => env('RABBITMQ_DSN', null),
            /*
             * Could be one a class that implements \Interop\Amqp\AmqpConnectionFactory for example:
             *  - \EnqueueAmqpExt\AmqpConnectionFactory if you install enqueue/amqp-ext
             *  - \EnqueueAmqpLib\AmqpConnectionFactory if you install enqueue/amqp-lib
             *  - \EnqueueAmqpBunny\AmqpConnectionFactory if you install enqueue/amqp-bunny
             */
            'factory_class' => Enqueue\AmqpLib\AmqpConnectionFactory::class,
            'host' => env('RABBITMQ_HOST', '127.0.0.1'),
            'port' => env('RABBITMQ_PORT', 5672),
            'vhost' => env('RABBITMQ_VHOST', '/'),
            'login' => env('RABBITMQ_LOGIN', 'user'),
            'password' => env('RABBITMQ_PASSWORD', 'secret_password'),
            'queue' => env('RABBITMQ_QUEUE', 'default'),
            'options' => [
                'exchange' => [
                    'name' => env('RABBITMQ_EXCHANGE_NAME'),
                    /*
                    * Determine if exchange should be created if it does not exist.
                    */
                    'declare' => env('RABBITMQ_EXCHANGE_DECLARE', true),
                    /*
                    * Read more about possible values at https://www.rabbitmq.com/tutorials/amqp-concepts.html
                    */
                    'type' => env('RABBITMQ_EXCHANGE_TYPE', \Interop\Amqp\AmqpTopic::TYPE_DIRECT),
                    'passive' => env('RABBITMQ_EXCHANGE_PASSIVE', false),
                    'durable' => env('RABBITMQ_EXCHANGE_DURABLE', true),
                    'auto_delete' => env('RABBITMQ_EXCHANGE_AUTODELETE', false),
                    'arguments' => env('RABBITMQ_EXCHANGE_ARGUMENTS'),
                ],
                'queue' => [
                    /*
                    * Determine if queue should be created if it does not exist.
                    */
                    'declare' => env('RABBITMQ_QUEUE_DECLARE', true),
                    /*
                    * Determine if queue should be binded to the exchange created.
                    */
                    'bind' => env('RABBITMQ_QUEUE_DECLARE_BIND', true),
                    /*
                    * Read more about possible values at https://www.rabbitmq.com/tutorials/amqp-concepts.html
                    */
                    'passive' => env('RABBITMQ_QUEUE_PASSIVE', false),
                    'durable' => env('RABBITMQ_QUEUE_DURABLE', true),
                    'exclusive' => env('RABBITMQ_QUEUE_EXCLUSIVE', false),
                    'auto_delete' => env('RABBITMQ_QUEUE_AUTODELETE', false),
                    'arguments' => env('RABBITMQ_QUEUE_ARGUMENTS'),
                ],
            ],
            /*
             * Determine the number of seconds to sleep if there's an error communicating with rabbitmq
             * If set to false, it'll throw an exception rather than doing the sleep for X seconds.
             */
            'sleep_on_error' => env('RABBITMQ_ERROR_SLEEP', 5),
            /*
             * Optional SSL params if an SSL connection is used
             */
            'ssl_params' => [
                'ssl_on' => env('RABBITMQ_SSL', false),
                'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
            ],

        ],

        'sync' => [
            'driver' => 'sync',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
        ],

        'beanstalkd' => [
            'driver' => 'beanstalkd',
            'host' => 'localhost',
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => 0,
        ],

        'sqs' => [
            'driver' => 'sqs',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'prefix' => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue' => env('SQS_QUEUE', 'your-queue-name'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            'block_for' => null,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging so you
    | can control which database and table are used to store the jobs that
    | have failed. You may change them to any database / table you wish.
    |
    */

    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],

];

```

**Comment by nanophp** [comment]
@vyuldashev even I have change 

`'host' => env('RABBITMQ_HOST', '127.0.0.1'), `

like this `'host' => env('RABBITMQ_HOST', 'rabbitmq'),`

**Comment by zaidhaider9** [comment]
was this resolved @valehasadli  @vyuldashev ? I am facing the same error, laravel 6

**Comment by valehasadli** [comment]
> was this resolved @valehasadli @vyuldashev ? I am facing the same error, laravel 6

Yeah, I was.
