### ISSUE TITLE
Add support for Correlational ID

### ISSUE THREAD

**Issue by CaporalDead** [vladimir-yuldashev/laravel-queue-rabbitmq#68]
Hi @vladimir-yuldashev,

I'm trying to add to laravel a way to support "correlational id" (as you can see here https://github.com/Devitek/laravel-correlational-id) and I'd like to add this feature to message queue with your package. You can find an example of this here https://www.sitepoint.com/php-rabbitmq-advanced-examples/. Do you have an idea to implement this feature with your package ? I will try to find a good way on my side but if you're interested by that let me know :).

**Comment by vladimir-yuldashev** [comment]
Why do we need that?

**Comment by CaporalDead** [comment]
The concept of the correlational ID is a convenient way to trace messages or log across multiple applications, For example, if you work on a micro service architecture with multiple APIs or using a queue and if you're using an ELK stack maybe, you can easily follow your request accross your APIs or daemons to find what's going on.

**Comment by vladimir-yuldashev** [comment]
Done thx to @dustindoiron.

**Comment by CaporalDead** [comment]
Thx @dustindoiron @vladimir-yuldashev !!! Didn't have the time to look @ it,
