### ISSUE TITLE
Doensn't work on laravel 5.3

### ISSUE THREAD

**Issue by GrahamCampbell** [vladimir-yuldashev/laravel-queue-rabbitmq#75]
Missing size method.

**Comment by vladimir-yuldashev** [comment]
I have not tested library on 5.3 yet. Where does it miss method `size`?

**Comment by dustindoiron** [comment]
@GrahamCampbell Lots of folks would love to upgrade to 5.3 as soon as it is released, and would like to help this library along in the process. Feedback like this is frustrating because it doesn't help that process. If this feedback were more detailed, including examples of the interface you're likely referencing, it'd be much more helpful. I hope you'll consider revising your feedback to better help contributors to this project.

**Comment by GrahamCampbell** [comment]
I'm telling you I added a size method to the queue contract. If you re-run travis, it should fail and show you what I mean.

**Comment by bryanashley** [comment]
I agree Graham, a simple re-run of travis would've highlighted this issue. This issue probably didn't even need to be reported.

**Comment by vladimir-yuldashev** [comment]
Calm down, guys :) Travis did not show anything because the library does not have tests.

**Comment by GrahamCampbell** [comment]
haha, lol :)

**Comment by tristanbailey** [comment]
Without stating the obvious, what should the size method do if you needed a PR for this?
Just poll the queue size or is it size of job?

**Comment by GrahamCampbell** [comment]
It gets the total size of the queue including reserved, late, whatever.

**Comment by shadoWalker89** [comment]
Any updates about this ?
I see that the size is still empty

**Comment by huglester** [comment]
@GrahamCampbell if you know what/where. Can you please be more descriptive?

**Comment by tristanbailey** [comment]
To point to the code, this is code that is not in the package yet. I am not sure how much it fails without it, as this has not been there for a while:

https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/master/tests/RabbitMQQueueTest.php

Tests this, but will not give anything as size() is not implimented
$this->queue->size()

https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/master/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/RabbitMQQueue.php

```

    /**
     * Get the size of the queue.
     *
     * @param  string $queue
     * @return int
     */
    public function size($queue = null)
    {
        // TODO: Implement size() method.
    }

```

**Comment by vladimir-yuldashev** [comment]
@tristanbailey It tests that calling it does not crash everything. I do not have much time for now to implement this. I spend only me free time. If you wish to help, please open PR.

**Comment by AaronJan** [comment]
So I made a [PR](https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/pull/127).
😉

**Comment by vladimir-yuldashev** [comment]
@AaronJan Solved this issue.
