### ISSUE TITLE
Fanout approach could not work

### ISSUE THREAD

**Issue by nickypeh** [vladimir-yuldashev/laravel-queue-rabbitmq#92]
Hi, 
I would like to use the fanout approach for the publish / subscribe as shown in this rabbitmq tutorial
[link here](https://www.rabbitmq.com/tutorials/tutorial-three-php.html)

In laravel 5.3 setup, i tried to setup with fanout exchange without naming the queue by leaving it blank string. Setting it up with exclusive as well. 

For my workers/ consumers, I am using supervisor to run with 5 processes. Hence , it would be 5 workers running the background. Once , supervisor is started, then it will create five temporary queues exclusively as shown in the rabbitmq tutorial as show above.

My expectation would be once a request sent to dispatch a job, then 5 processes would take it up and process 5 times. However, once the job is dispatched but no processes pick it up. 

Is there something wrong with the setup ? 

So far, it could work best if queue name is setup properly with only one message with one worker to handle it. 
1. Direct Exchange
2. Fanout Exchange with proper queue name

My connection is shown as below : 

`'rabbitmq' => [
            'driver' => 'rabbitmq',
            'host' => env('RABBITMQ_HOST', '127.0.0.1'),
            'port' => env('RABBITMQ_PORT', 5672),
            'vhost'    => env('RABBITMQ_VHOST', '/'),
            'login'    => env('RABBITMQ_LOGIN', 'guest'),
            'password' => env('RABBITMQ_PASSWORD', 'guest'),
            'queue' => '',
            'exchange_declare' => env('RABBITMQ_EXCHANGE_DECLARE', true),
            'queue_declare_bind' => env('RABBITMQ_QUEUE_DECLARE_BIND', true),
            'queue_params' => [
                'passive'     => env('RABBITMQ_QUEUE_PASSIVE', false),
                'durable'     => env('RABBITMQ_QUEUE_DURABLE', true),
                'exclusive'   => true,
                'auto_delete' => env('RABBITMQ_QUEUE_AUTODELETE', false),
            ],
            'exchange_params' => [
                'name' => 'fanout_testing',
                'type' => 'fanout',
                'passive' => env('RABBITMQ_EXCHANGE_PASSIVE', false),
                'durable' => true,
                'auto_delete' => env('RABBITMQ_EXCHANGE_AUTODELETE', false),
            ],
        ]`

**Comment by EwanValentine** [comment]
Did you find a solution to this?
