### ISSUE TITLE
Multiple RabbitMQ Connections and Queues?

### ISSUE THREAD

**Issue by Rolice** [vladimir-yuldashev/laravel-queue-rabbitmq#93]
Hello,
I am creating application that should be able to connect to different vhosts in RabbitMQ and respectively different queues inside. My idea is that in a Laravel project to define separate RabbitMQ queue for each VHost.

Shoud I add separate connector as done in the service provider or there is any other better way? I am not quite experienced with the queues that is why I am asking? I will continue digging meanwhile.

Thank you.

**Comment by vladimir-yuldashev** [comment]
Different connection. And provide connection option in your worker.

**Comment by Rolice** [comment]
Thank you.

I have added the connections previously but I have seen the options (--queue, etc.) but missed the connection argument for artisan commands about queues... Thank you very much, it worked properly.
