### ISSUE TITLE
Message Acknowledgement

### ISSUE THREAD

**Issue by Rolice** [vladimir-yuldashev/laravel-queue-rabbitmq#95]
Hello,
I am writing again with question after I have managed to create multiple queue connections to rabbmitMQ server, after your response to my question. :)

Now I have an issue with acknowledgement of messages. It appear that the message is received and processed by a Job (the job is not regular RabbitMQ job, but my implementations, since the message JSON refer to a job of mine, like:

``` json
{
    "job": "Somenamespace\\SomeJob@handle",
    "data": {
        "param1": "asd",
        "param2": "asd"
    }
}
```

I receive in my `handle` method two arguments. First is the generic RabbitMQJob and the second is the actial payload from the `data` field in the message (see JSON above).

``` php
    /**
     * Execute the job.
     *
     * @param RabbitMQJob $job
     * @param array $payload
     */
    public function handle($job, $payload)
    {
        // Do the actual processing of the payload and take the respective actions...
        $job->delete(); // Do I have to call this at the end?
    }
```

Do I have to call `$job->delete` to release the message from the queue? It appears working this way and is the proper way of working?

**PS**: I am not sure if I am taking full advantage of the package in a proper way, with this usage...

Thank you!

**Comment by Rolice** [comment]
I have checked the approach above. It is not enough to call the `delete` method. It appears that the message is treated as unacknowledged and it is returned after being processed. Which is strange, could be configuraiton issue? I have used the configuration from the example `queue.php` file.

What I have checked and appears to be working is to modify the `RabbitMQQueue` - `pop` method:

```php
        $message = $this->channel->basic_get($queue); // ORIGINAL
```
like:
```php
        $message = $this->channel->basic_get($queue, true); // Second parameter 'no_ack' to true.
```
This way I am getting messages from the queue with no acknowledgement and works, but seem to me very **hacky** solution.

Do you have any ideas how can acknowledge message simply from my job?

Regards

**Comment by Rolice** [comment]
@vladimir-yuldashev, did you have time to review this question?

**Comment by vladimir-yuldashev** [comment]
@Rolice Sorry for late answer. If you set `no_ack` to true it would no be deleted as `no_ack` is no acknowledgement. 

Which version of Laravel do you use? `handle` method with `$job` and `$payload` looks like an old approach. If you use Laravel < 5.0 then you need to call `delete` method in order the job to be deleted. In version >= 5.0 it is being deleted automatically if no exception is thrown.

**Comment by Rolice** [comment]
Hello I found that the issue was caused by an unhandled exceptions thrown by a third-party packages like ones that communicate with service via API and there are some 404 errors, etc.

Thank you for your answer!
