### ISSUE TITLE
Default attempt should be 1

### ISSUE THREAD

**Issue by duynguyenhoang** [vladimir-yuldashev/laravel-queue-rabbitmq#96]
Hi, 

Look like Laravel use **1** as default number of attempt

Please check here https://github.com/laravel/framework/blob/5.2/src/Illuminate/Queue/RedisQueue.php#L255

I will open pull request for it.

**Comment by sweetvvck** [comment]
@duynguyenhoang are you still working on this ?

**Comment by duynguyenhoang** [comment]
@sweetvvck I will open pull request with in today, do you need anything more?

**Comment by sweetvvck** [comment]
@duynguyenhoang i think it's not good to use `$attempts` property in RabbitMQQueue to count attempts of job even if it works well by now.

**Comment by duynguyenhoang** [comment]
https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq/blob/66e35bc09480f8cd212f528c744da694bff00c60/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php#L62

This is what i mean, default Laravel Redis return 1, but in here, it is 0. I mean that we need to make they are consistent for all adapters.

**Comment by sweetvvck** [comment]
i knew what you mean, besides i thought the way [vladimir-yuldashev/laravel-queue-rabbitmq](https://github.com/vladimir-yuldashev/laravel-queue-rabbitmq) count job attempts is not good.

**Comment by vladimir-yuldashev** [comment]
Merged, in 5.3 release.
