### ISSUE TITLE
Add a routing key to a queued job

### ISSUE THREAD

**Issue by EwanValentine** [vladimir-yuldashev/laravel-queue-rabbitmq#98]
Is it possible to define a routing key for a queued job with this library? I have several bots listening to the same queue, but need to use the routing key to map the Laravel queued job to the correct bot.

**Comment by vladimir-yuldashev** [comment]
Routing key is set automatically using your queue's name. If you need an option to override it, please make a PR.

**Comment by JABvzla** [comment]
I supposed this [commit](https://github.com/vyuldashev/laravel-queue-rabbitmq/commit/ba427c094369cdfac5898801a8fee739d7708128) allow set a `routing_key` but i dont understand how set that props.

**Comment by krodney** [comment]
@JABvzla set a `routing_key` inside the `options` array in your config like this...
```
...
'options' => [
    ...
    'routing_key' => 'my_key',
    ...
],
...
```

**Comment by vlauciani** [comment]
> I supposed this [commit](https://github.com/vyuldashev/laravel-queue-rabbitmq/commit/ba427c094369cdfac5898801a8fee739d7708128) allow set a `routing_key` but i dont understand how set that props.

Yes, looking the code:
- https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/src/Queue/RabbitMQQueue.php#L82

seems that `'routing_key' => 'my_key'` options is the solution, but It doesn't work (for me); sending a message on a `foo` queue, the `routing_key` is set automatically to `foo`.
