### ISSUE TITLE
How can dead lettering be configured?

### ISSUE THREAD

**Issue by andrefigueira** [vladimir-yuldashev/laravel-queue-rabbitmq#99]
Hi there, 

I've noticed you declare dead letter headers:

```
'x-dead-letter-exchange' => $destinationExchange,
'x-dead-letter-routing-key' => $destination,
'x-message-ttl' => $delay * 1000,
```

How can I configure my install to use this and not the failed_jobs table?

Edit:

Just realised, that's for delayed publishing, if I was to make a pull request which adds the ability to override the failed_jobs, by using a RMQ dead queue instead, would this be something you'd be interested in including in the project? 

I need this for a big project that'll be handling millions of jobs, and if something goes wrong, I don't want MySQL to become a bottleneck

**Comment by vladimir-yuldashev** [comment]
I think it will make delayed jobs non-working.

**Comment by andrefigueira** [comment]
You sure? Just thinking on the basis of being able to log failed jobs on a system with much higher loads, wouldn't really want all of that going to mysql, could make it so that if delayed jobs are enabled, dead queue would be disabled?
